spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/apipokemon
        username: postgres
        password: senha
    jpa:
        show-sql: false
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
        ddl-auto: update
